config/routes.rb
Rails.application.routes.draw do
  resources :home, only: [:index]
  root to: 'home#index'
  post '/', to: 'home#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }, skip: [:registrations, :passwords]

  resources :users
  resources :profiles


end

app/models/profile.rb
class Profile < ApplicationRecord
  before_update :remove_existing_permissions

  has_many :permissions, class_name: 'Acl::Permission', dependent: :delete_all
  accepts_nested_attributes_for :permissions, reject_if: proc { |attributes| attributes['actions'].blank? }

  validates :name, presence: true
  validates :name, uniqueness: true

  def has_action(app_module_id, action)
    permission = self.permissions.where(app_module_id: app_module_id).first
    return permission.present? ? permission.actions.include?(action) : false
  end

  private
    def remove_existing_permissions
      Acl::Permission.where(profile_id: self.id).delete_all
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :verify_modules, only: [:new, :edit]

  # GET /profiles
  # GET /profiles.json
  def index
    @q = Profile.ransack(params[:q])
    @profiles = @q.result(distinct: true)
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: translate_message(:created) }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: translate_message(:updated) }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: translate_message(:destroyed) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :admin, permissions_attributes: [ :id, :app_module_id, actions: [] ])
    end

    def verify_modules
      Acl::AppModule.verify_modules
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<% content_for :header_page do %>
  <%= render 'layouts/helpers/title_page', model: :profile %>
<% end %>

<!-- form start -->
<%= form_with(model: profile, local: true, class: "form-horizontal") do |f| %>
  
  <div class="row">
    <div class="col-12">

      <%= render  'layouts/helpers/error', object: profile %>

      <div class="card">
        <div class="card-header">
          <h3 class="card-title"><%= translate_action(action) %></h3>
        </div>
        <!-- /.card-header -->

          <div class="card-body">
            
            <div class="form-group row">
              <label class="col-sm-2 control-label text-right"><%= translate_attr(:name, :profile) %></label>
              <div class="col-sm-9">
                <%= f.text_field :name, id: :profile_name, class: "form-control" %>
              </div>
            </div>

            <div class="form-group row">
              <label class="col-sm-2"></label>
              <div class="form-check col-sm-9">
                <%= f.check_box :admin, id: :profile_admin, class: "form-check-input" %>
                <%= translate_attr(:admin, :profile) %>
              </div>
            </div>
          </div>
          <!-- /.card-body -->
      </div><!--/.card-->
    </div><!--/.col-12-->

    <div class="col-12">
      <h3>Módulos</h3>
    </div><!--/col-12-->

    <% Acl::AppModule.all.each_with_index do |m, i| %>
      <div class="col-md-6">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title"><%= translate_module(m.module) %></h3>
          </div>
          <!-- /.card-header -->

          <div class="card-body">
            <div class="form-group">
              <div class="col-12">
                <%= hidden_field_tag "profile[permissions_attributes][#{i}]app_module_id", m.id %>
                <select name="profile[permissions_attributes][<%= i %>]actions[]" title="Selecionar ..."
                  class="selectpicker form-control" data-actions-box="true" multiple>
                  <optgroup label="<%= translate_module(m.module) %>">
                    <% m.actions.each do |action| %>
                      <option value="<%= action %>" <%= 'selected' if @profile.has_action(m.id, action) %>
                      data-icon="fa fa-arrow-circle-o-right"><%= translate_action(action) %></option>
                    <% end %>
                  </optgroup>
                </select>
              </div>
            </div><!-- /.form-group -->

          </div><!-- /.card-body -->
        </div><!--/.card-->
      </div><!--/.col-md-6-->
    <% end %>

    <div class="col-12">
      <%= link_to translate_action(:back), profiles_path, class: "btn btn-default" %>
      <button type="submit" class="btn btn-info float-right"><%= translate_action(btn_action) %></button>
    </div><!--/.col-12-->

  </div><!--/.row-->
<% end %>

app/views/profiles/edit.html.erb
<%= render 'form', profile: @profile, action: :edit, btn_action: :update %>

app/views/profiles/index.html.erb
<%= render 'layouts/helpers/index',
    model: :profile,
    controller: :profiles,
    attributes: [:name, :admin],
    actions: [:show, :edit, :delete],
    delete_identification: :name,
    collection: @profiles,
    search_match: :name_cont %>

app/views/profiles/new.html.erb
<%= render 'form', profile: @profile, action: :new, btn_action: :create %>

app/views/profiles/show.html.erb
<div class="box box-default">
  <div class="box-header with-border">
    <h3 class="box-title">
      <%= translate_module(:profile, :one) %>
      <small><%= translate_action(:show) %></small>
    </h3>
  </div>
  <div class="box-body">
    <form class="form-horizontal">
      <div class="form-group">
        <label class="col-sm-2 control-label"><%= translate_attr(:name, :profile) %></label>
        <div class="col-sm-10">
          <p class="form-control-static"><%= @profile.name %></p>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 control-label"><%= translate_attr(:admin, :profile) %></label>
        <div class="col-sm-10">
          <p class="form-control-static"><%= @profile.admin ? 'SIM' : 'NÃO' %></p>
        </div>
      </div>

      <% unless @profile.permissions.empty? %>
        <h4 class="page-header text-muted">Módulos</h4>
      <% end %>

      <% @profile.permissions.each do |permission| %>
        <div class="form-group">
          <label class="col-sm-2 control-label"><%= translate_module(permission.app_module.module) %></label>
          <div class="col-sm-10">
            <p class="form-control-static"><%= permission.actions.map{|a| translate_action(a)}.to_s %></p>
          </div>
        </div>
      <% end %>

    </form>
  </div>
  <div class="box-footer">
    <%= link_to translate_action(:back), profiles_path, class: "btn btn-default" %>
    <%= link_to translate_action(:edit), edit_profile_path(@profile), class: "btn btn-info pull-right" %>
  </div><!-- /.box-footer -->
</div>